[project]
name = "api-rerank-ebm"
version = "0.1.0"
description = "API for rerank RAGFlow"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "uvicorn>=0.40.0",
]
